# Site settings
title: Saleem Toure Issifou
email: saleemtoure.work@uio.no
url: https://github.com/saleemtoure
description: "Saleem Toure Issifou Programming Portfolio"
keywords: "Python, Java, Software Engineering, Digital Economics"
skills: "Student - 20 <br> Informatics: Digital Economy and Leadership (Bachelor 2023-2026) <br> University of Oslo  "
meta_author: Issifou Saleem Toure

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:


contact: static


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 282A36 #Body + txt highlight - Dark grey/blue 
  primary-rgb: "194, 196, 211"  #Post highlight color - Grey
  secondary: 393f5b #Navbar & footer - Gray/Blueish
  secondary-dark: 282A36  #Highlight section when scrolling - - Dark grey/blue

# Footer settings
footer:
  copyright: Saleem Toure
  location: Location
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/saleemtoure
  - title: linkedin
    url: https://www.linkedin.com/in/saleem-toure-issifou/

# Postal address (add as many lines as necessary)
address:
  - line: Oslo, Norway

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
