# Site settings
title: Saleem Toure Issifou
email: saleemtoure.work@uio.no
url: https://github.com/saleemtoure
description: "Saleem Toure Issifou Programming Portfolio"
keywords: "Python, Java, Software Engineering, Digital Economics"
skills: "Student - 19 <br> 1. Year Bachelor <br> University of Oslo <br> Informatics: Digital Economy and Leadership"
meta_author: Issifou Saleem Toure

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 17181f #Navbar
  primary-rgb: "23,24,31"  #navbar
  secondary: F176C2 #Txt highlight cover
  secondary-dark: 282A36  #Body color

# Footer settings
footer:
  copyright: Saleem Toure
  location: Location
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/saleemtoure
  - title: linkedin
    url: https://www.linkedin.com/in/saleem-toure-issifou/

# Postal address (add as many lines as necessary)
address:
  # - line: 3481 Melrose Place
  # - line: Beverly Hills, CA 90210
  - line: Oslo, Norway

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
